name: flutter_app
description: A new Flutter application.
version: 1.6.5+bloc-subscription

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1
  path_provider: ^2.0.1
  rxdart: ^0.28.0
  window_manager: ^0.4.3
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2

  path: any
  drift: ^2.20.1
  drift_flutter: ^0.2.0
  go_router: ^14.3.0
  equatable: ^2.0.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  syncfusion_flutter_datagrid: ^29.1.35
  logger: ^2.4.0
  image_picker: ^1.0.0
  badges: ^3.1.2
  settings_ui: ^2.0.2
  file_picker: ^10.0.0
  provider: ^6.1.2
  enum_to_string: ^2.0.1

  flutter_localization: ^0.3.2
  intl: any
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  image_cropper: ^9.1.0
  flutter_local_notifications: ^17.2.1+2
  workmanager: ^0.9.0+2
  timezone: 0.9.4
  dio: ^5.9.0
  package_info_plus: ^8.3.1
  pub_semver: ^2.2.0
  flutter_downloader: ^1.12.0
  open_filex: ^4.7.0
  connectivity_plus: ^6.1.5
  receive_sharing_intent: ^1.8.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.19.5
  mockito: ^5.1.0
  build_runner: ^2.4.12
  drift_dev: ^2.20.2
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/twitter_logo.png
    - assets/facebook_logo.png
    - assets/stack_overflow.png
    - assets/Agnimon.jpg
    - assets/empty.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
